server:
  port: 80
  servlet:
    context-path: /cmfz
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 100GB
  redis:
    host: 192.168.248.22 # IP
    port: 4399 # 端口号
    database:  0 # 数据库
mybatis:
  mapper-locations: classpath:cn/liu/mapper/*.xml
  type-aliases-package: cn.liu.entity
logging:
  level:
    root: error
    cn.liu.dao: debug


